services:
  marimo:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: marimo edit --host 0.0.0.0 --port 8080 --no-token
    ports:
      - "8080:8080"
    volumes:
      - .:/app